classdef TimeSeriesIForestDetector < anomalyCLI.coder.mlanomaly.AbstractMachineLearningAnomalyDetector
    %#codegen

%   Copyright 2026 The MathWorks, Inc.

    methods

        function obj = TimeSeriesIForestDetector(opts)
            coder.internal.prefer_const(opts)
            obj@anomalyCLI.coder.mlanomaly.AbstractMachineLearningAnomalyDetector(opts);
        end
    end

    methods(Static,Hidden)
        function props = matlabCodegenNontunableProperties(~)
            props = anomalyCLI.coder.mlanomaly.AbstractMachineLearningAnomalyDetector.matlabCodegenNontunableProperties;
        end

        function name = matlabCodegenUserReadableName()
            % The below name will appear in the report generated by coder.
            name = 'TimeSeriesIForestDetector';
        end

        function cgObj = matlabCodegenToRedirected(mlObj)
            anomalyCLI.internal.utils.TimeSeriesAnomalyProcessing.validateTrained(mlObj.IsTrained);
            opts.NumChannels = mlObj.NumChannels;
            opts.WindowLength =  mlObj.WindowLength;
            opts.DetectionStride =  mlObj.DetectionStride;
            opts.Normalization = mlObj.Normalization;
            opts.FeatureExtraction = mlObj.FeatureExtraction;
            opts.Threshold = mlObj.Threshold;

            opts.pModel = mlObj.getUnderlyingModel;
            [opts.pDataCenter,opts.pDataScale] = getNormalizationParameters(mlObj);
            opts.pValidFeatureColumns =  getValidFeatureColumns(mlObj);
            cgObj = anomalyCLI.coder.mlanomaly.TimeSeriesIForestDetector(opts);
        end
    end
end
