classdef UsadDetector < anomalyCLI.coder.deepanomaly.AbstractDeepAnomalyDetector 
    %#codegen

    %   Copyright 2025-2026 The MathWorks, Inc.
    
    properties(SetAccess=private)
        DetectionWindowLength
        Alpha
        Beta
        pDlnetE
        pDlnetD1
        pDlnetD2
    end

    methods

        function this = UsadDetector(myProps,baseProps)            
            coder.internal.prefer_const(myProps,baseProps);

            % construct base class first.
            this@anomalyCLI.coder.deepanomaly.AbstractDeepAnomalyDetector(baseProps);

            pnames = fieldnames(myProps);
            coder.unroll();
            for i = 1:numel(pnames)
                this.(pnames{i}) = myProps.(pnames{i});
            end
            
        end

        function [dataArray,targetArray, segmentInfo, dataCell] = iPreProcessData(this, data, stride)
            coder.internal.prefer_const(data,stride);
            anomalyCLI.internal.utils.TimeSeriesAnomalyProcessing.validateInputData(...
                data, this.NumChannels,this.DetectionWindowLength, this.DetectionStride);
            doNormalization = coder.const(~strcmp(this.Normalization,'off'));
            [dataArray,segmentInfo,dataCell] = anomalyCLI.coder.utils.preprocessInputData(...
                data,this.DetectionWindowLength,stride, doNormalization,this.DataCenter,this.DataScale);
            targetArray = [];
        end

        function winScores = iGetWinScores(this,datain,~,options)
            arguments
                this
                datain
                ~
                options.MiniBatchSize
            end
            data = dlarray(datain,'SCB');

            miniBatchSize = coder.internal.indexInt(options.MiniBatchSize);
            customMiniBatchPredict = @anomalyCLI.coder.utils.miniBatchPredictSCB;
            Z = customMiniBatchPredict(this.pDlnetE,data,miniBatchSize);
           
            Y1 = customMiniBatchPredict(this.pDlnetD1,Z,miniBatchSize);

            Y1_ = dlarray(reshape(Y1,this.DetectionWindowLength,this.NumChannels,size(Y1,2)),'SCB');

            Z_ = customMiniBatchPredict(this.pDlnetE,Y1_,miniBatchSize);
            Y2 = customMiniBatchPredict(this.pDlnetD2,Z_,miniBatchSize);

            Y2_ = dlarray(reshape(Y2,this.DetectionWindowLength,this.NumChannels,size(Y2,2)),'SCB');

            winError = this.Alpha*mean((data-Y1_).^2,1) + this.Beta*mean((data-Y2_).^2);

            aggregateError = squeeze(extractdata(mean(winError,2)));

            winScores = double(gather(aggregateError));
        end
    end

    methods(Static,Hidden)
        function props = matlabCodegenNontunableProperties(~)
            props = [{'DetectionWindowLength'},...
                anomalyCLI.coder.deepanomaly.AbstractDeepAnomalyDetector.matlabCodegenNontunableProperties];
        end

        function name = matlabCodegenUserReadableName()
            % The below name will appear in the report generated by coder.
            name = 'UsadDetector';
        end

        function cgObj = matlabCodegenToRedirected(mlObj)
            anomalyCLI.internal.utils.TimeSeriesAnomalyProcessing.validateTrained(...
                mlObj.IsTrained);

            myProps.DetectionWindowLength = mlObj.DetectionWindowLength;
            myProps.Alpha = mlObj.Alpha;
            myProps.Beta = mlObj.Beta;
            [myProps.pDlnetE, myProps.pDlnetD1, myProps.pDlnetD2] = deal(mlObj.Dlnet{:});
             
            % Base class properties.
            baseProps.NumChannels = mlObj.NumChannels;
            baseProps.Threshold = mlObj.Threshold;
            baseProps.Normalization = mlObj.Normalization;
            baseProps.DetectionStride = mlObj.DetectionStride;
            [baseProps.DataCenter, baseProps.DataScale] = mlObj.getNormalizationParameters();
            cgObj = anomalyCLI.coder.deepanomaly.UsadDetector(myProps,baseProps);
        end

    end
end
