classdef TcnDetector < anomalyCLI.coder.deepanomaly.AbstractDeepAnomalyDetector  
%#codegen

%   Copyright 2025-2026 The MathWorks, Inc.

    properties (SetAccess = private)
        DetectionWindowLength
        Dlnet
        WindowScoresAggregationMethod
    end

    methods
        function this = TcnDetector(myProps,baseProps)
            coder.internal.prefer_const(myProps,baseProps);
            
            % construct base class first.
            this@anomalyCLI.coder.deepanomaly.AbstractDeepAnomalyDetector(baseProps);

            pnames = fieldnames(myProps);
            coder.unroll();
            for i = 1:numel(pnames)
                this.(pnames{i}) = myProps.(pnames{i});
            end
        end

        function [dataArray, targetArray,segmentInfo, dataCell] = iPreProcessData(this, data, stride)
            coder.internal.prefer_const(stride);
            anomalyCLI.internal.utils.TimeSeriesAnomalyProcessing.validateInputData(...
                data, this.NumChannels,this.DetectionWindowLength, this.DetectionStride);
            doNormalization = coder.const(~strcmp(this.Normalization,'off'));
            [dataArray,segmentInfo,dataCell] = anomalyCLI.coder.utils.preprocessInputData(...
                data,this.DetectionWindowLength,stride, doNormalization,this.DataCenter,this.DataScale);
            targetArray = [];
        end

        function winScores = iGetWinScores(this,data,~,options)
            arguments
                this
                data
                ~
                options.MiniBatchSize
            end
            coder.internal.prefer_const(options)
            reconstructedTarget = anomalyCLI.coder.utils.miniBatchPredictTCB(...
                this.Dlnet,data,options.MiniBatchSize);
            pointScores = iComputeAnomalyScore(this,data,reconstructedTarget);
            winScores = double(iAggregatePointScores(this,pointScores));
        end

        function pointScores = iComputeAnomalyScore(~,data, reconstructedTarget)
            numObservations = coder.internal.indexInt(size(data,3));
            pointScores = coder.nullcopy(repmat({zeros(size(data,1),1,"like",data)},numObservations,1));
            for i = 1:numObservations
                pointScores{i} = sqrt(sum((data(:,:,i) - reconstructedTarget(:,:,i)).^2,2));
            end
        end

        function winScores = iAggregatePointScores(obj,pointScores)
            fun = coder.const(str2func(obj.WindowScoresAggregationMethod));
            winScores = cellfun(fun,pointScores,'UniformOutput',true);
        end
    end

    methods(Static,Hidden)
        
        function props = matlabCodegenNontunableProperties(~)
            % In code generation, assigning a constant value to a class property
            % alone does not make it a constant, this special method returns
            % the names of properties that we want to be constant, MATLAB
            % Coder specifically looks for these properties and force them
            % to be constant.
            props = [{'DetectionWindowLength','WindowScoresAggregationMethod'},...
                    anomalyCLI.coder.deepanomaly.AbstractDeepAnomalyDetector.matlabCodegenNontunableProperties];              
        end

        function name = matlabCodegenUserReadableName()
            % The below name will appear in the report generated by coder.
            name = 'TcnDetector';
        end

        function cgObj = matlabCodegenToRedirected(mlObj)
            % mlObj is the TcnDetector object saved in the matfile. This
            % method is automatically invoked during coder load. Here we
            % convert MATLAB's TcnDetector object to its coder implementation
            %
            % Detector must be trained to be used in inference.            
            anomalyCLI.internal.utils.TimeSeriesAnomalyProcessing.validateTrained(...
                mlObj.IsTrained);
            % Concrete class properties
            myProps.DetectionWindowLength = mlObj.DetectionWindowLength;
            myProps.WindowScoresAggregationMethod = mlObj.getWindowScoresMethod();
            myProps.Dlnet = mlObj.Dlnet;
            % Base class properties.
            baseProps.NumChannels = mlObj.NumChannels;
            baseProps.Threshold = mlObj.Threshold;
            baseProps.Normalization = mlObj.Normalization;
            baseProps.DetectionStride = mlObj.DetectionStride;
            [baseProps.DataCenter, baseProps.DataScale] = mlObj.getNormalizationParameters();
            cgObj = anomalyCLI.coder.deepanomaly.TcnDetector(myProps,baseProps);
        end

    end
end
