classdef TS_DeepAnT
    %Static utility class for DeepAnT model
    %related functionalities like constructing the training & detection
    %configuration panel along with the train and detect actions

%   Copyright 2025-2026 The MathWorks, Inc.

    properties (Constant)
        Name (1,1) string = m('predmaint_anomaly:anomaly_app:strDeepAnT')
        Description (1,1) string = m('predmaint_anomaly:anomaly_app:tipDeepAnT')
        Type (1,1) string = "deepant"
        IconName (1,1) string = "convolution1d"

        %Overview Panel
        ScoringDescription (1,1) string = m('predmaint_anomaly:anomaly_app:descDeepAnT');
        BestSuitedDescription (1,1) string = m('predmaint_anomaly:anomaly_app:bestSuitedDeepAnT');
        TuningRecommendationDescription (1,1) string = m('predmaint_anomaly:anomaly_app:tuningRecommendationDeepAnT');
        
        % Defaults aligned with control IDs
        defaultModelConfig (1,1) struct = struct(...
            'ObservWindowLengthSpinner', 100, ...
            'TrainingStrideSpinner', 10, ...
            'DetectWindowLengthSpinner', 10, ...
            'MaxEpochsSpinner', 10, ...
            'LearnRateSpinner', 0.001, ...
            'BatchSizeSpinner', 256, ...
            'ExecEnvDropdown', 'auto', ...
            'NormalizeDropdown', 'zscore', ...
            'FilterSizeSpinner', 3, ...
            'NumFiltersSpinner', 32, ...
            'DropoutSpinner', 0.25, ...
            'SolverDropdown', 'adam')

        defaultDetectConfig (1,1) struct = struct(...
            'DetectionStrideSpinner', 10, ...
            'ThresholdMethodDropdown', 'kSigma', ...
            'ThresholdParamSpinner', 3, ...
            'ThresholdSpinner', 1, ...
            'BatchSizeSpinner', 256,...
            'ExecEnvDropdown', 'auto')

        %Detector Type
        DetectorType (1,1) string = "DeepLearning"
    end

    methods (Static)
        function createTrainOptionsPanel(PanelOptionsObj, ModelStore, modelName)
            import anomalyAPP.internal.app.modelmanager.utils.*
            import anomalyAPP.internal.app.modelmanager.TS_DeepAnT

            weak_obj = matlab.lang.WeakReference(PanelOptionsObj);
            wd = PanelOptionsObj.Widgets;
            mainGrid = wd.MainGrid;

            % --- Training Options ---
            trainingGrid = UiWidgetFactory.createGrid(mainGrid, m('predmaint_anomaly:anomaly_app:strTrainingOptions'), 1, 4, Tag="TrainOptsGrid");

            % Max Epochs
            UiWidgetFactory.createLabel(trainingGrid, ...
                m('predmaint_anomaly:anomaly_app:strMaxEpochs'), 1, ...
                m('predmaint_anomaly:anomaly_app:configTooltipMaxEpochs'));
            limits = [0.9 inf];
            step = 1;
            row = 1;
            roundFractional = true;
            maxEpochsSpinner = UiWidgetFactory.createSpinner(trainingGrid, limits, ...
                TS_DeepAnT.defaultModelConfig.MaxEpochsSpinner, step, row, roundFractional);
            maxEpochsSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'MaxEpochsSpinner');

            % Learning Rate
            UiWidgetFactory.createLabel(trainingGrid, ...
                m('predmaint_anomaly:anomaly_app:strInLR'), 2, ...
                m('predmaint_anomaly:anomaly_app:configTooltipInitialLearnRate'));
            limits = [0 inf];
            step = 0.001;
            row = 2;
            roundFractional = false;
            learnRateSpinner = UiWidgetFactory.createSpinner(trainingGrid, limits, ...
                TS_DeepAnT.defaultModelConfig.LearnRateSpinner,step, row, roundFractional);
            learnRateSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'LearnRateSpinner');

            % Batch Size
            UiWidgetFactory.createLabel(trainingGrid, ...
                m('predmaint_anomaly:anomaly_app:strMiniBatchSize'), 3, ...
                m('predmaint_anomaly:anomaly_app:configTooltipMiniBatchSize'));
            limits = [0.9 inf];
            step = 10;
            row = 3;
            roundFractional = true;
            batchSizeSpinner = UiWidgetFactory.createSpinner(trainingGrid, limits, ...
                TS_DeepAnT.defaultModelConfig.BatchSizeSpinner, step, row, roundFractional);
            batchSizeSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'BatchSizeSpinner');

            % Execution Environment
            UiWidgetFactory.createLabel(trainingGrid, ...
                m('predmaint_anomaly:anomaly_app:strExecEnv'), 4,...
                m('predmaint_anomaly:anomaly_app:configTooltipExecutionEnvironment'));
            execEnvDropdown = UiWidgetFactory.createDropdown(trainingGrid, ...
                [m('predmaint_anomaly:anomaly_app:strAuto'), ...
                m('predmaint_anomaly:anomaly_app:strCpu'), ...
                m('predmaint_anomaly:anomaly_app:strGpu'), ...
                m('predmaint_anomaly:anomaly_app:strMultigpu')], ...
                {'auto','cpu','gpu','multi-gpu'}, ...
                TS_DeepAnT.defaultModelConfig.ExecEnvDropdown, 4, false);
            execEnvDropdown.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'ExecEnvDropdown');

            % Solver Name
            UiWidgetFactory.createLabel(trainingGrid, ...
                m('predmaint_anomaly:anomaly_app:strSolverName'), 5,...
                m('predmaint_anomaly:anomaly_app:configTooltipSolverName'));
            solverDropdown = UiWidgetFactory.createDropdown(trainingGrid, [...
                m('predmaint_anomaly:anomaly_app:strSolverSgdm'), ...
                m('predmaint_anomaly:anomaly_app:strSolverAdam'), ...
                m('predmaint_anomaly:anomaly_app:strSolverRmsprop'), ...
                m('predmaint_anomaly:anomaly_app:strSolverLbfgs'), ...
                m('predmaint_anomaly:anomaly_app:strSolverLm')], ...
                {'sgdm','adam','rmsprop','lbfgs','lm'}, ...
                TS_DeepAnT.defaultModelConfig.SolverDropdown, 5, false);
            solverDropdown.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'SolverDropdown');

            % --- Model Options ---
            modelGrid = UiWidgetFactory.createGrid(mainGrid, m('predmaint_anomaly:anomaly_app:strModelOptionsTitle'), 2, 5, Tag="ModelOptsGrid");

            % Normalization
            UiWidgetFactory.createLabel(modelGrid, ...
                m('predmaint_anomaly:anomaly_app:strNormalizeData'), 1,...
                m('predmaint_anomaly:anomaly_app:configTooltipNormalizeData'));
            normalizeDropdown = UiWidgetFactory.createDropdown(modelGrid, ...
                [m('predmaint_anomaly:anomaly_app:strZscore'), ...
                m('predmaint_anomaly:anomaly_app:strRange'), ...
                m('predmaint_anomaly:anomaly_app:strOff')], ...
                {'zscore','range','off'}, ...
                TS_DeepAnT.defaultModelConfig.NormalizeDropdown, 1, false);
            normalizeDropdown.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'NormalizeDropdown');

            % Observation Window Length
            UiWidgetFactory.createLabel(modelGrid, ...
                m('predmaint_anomaly:anomaly_app:strObservWL'), 2,...
                m('predmaint_anomaly:anomaly_app:configTooltipObservationWindowLength'));
            limits = [1 inf];
            step = 1;
            row = 2;
            roundFractional = true;
            observWindowLengthSpinner = UiWidgetFactory.createSpinner(modelGrid, limits, ...
                TS_DeepAnT.defaultModelConfig.ObservWindowLengthSpinner, step, row, roundFractional);
            observWindowLengthSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'ObservWindowLengthSpinner');

            % Training Stride
            UiWidgetFactory.createLabel(modelGrid, ...
                m('predmaint_anomaly:anomaly_app:strTrainingStride'), 3,...
                m('predmaint_anomaly:anomaly_app:configTooltipTrainingStride'));
            limits = [1 inf];
            step = 1;
            row = 3;
            roundFractional = true;
            upperLimitInclusive = false;
            lowerLimitInclusive = true;
            trainingStrideSpinner = UiWidgetFactory.createSpinner(modelGrid, limits, ...
                TS_DeepAnT.defaultModelConfig.TrainingStrideSpinner, step, row, ...
                roundFractional, upperLimitInclusive, lowerLimitInclusive);
            trainingStrideSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'TrainingStrideSpinner');

            % Detection Window Length
            UiWidgetFactory.createLabel(modelGrid, ...
                m('predmaint_anomaly:anomaly_app:strDetectWL'), 4, ...
                m('predmaint_anomaly:anomaly_app:configTooltipDetectionWindowLength'));
            limits = [0.9 inf];
            step = 1;
            row = 4;
            roundFractional = true;
            detectWindowLengthSpinner = UiWidgetFactory.createSpinner(modelGrid, limits, ...
                TS_DeepAnT.defaultModelConfig.DetectWindowLengthSpinner, step, row, roundFractional);
            detectWindowLengthSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'DetectWindowLengthSpinner');

            % Advanced Options (Accordion)
            advancedGrid = UiWidgetFactory.createAccordion(modelGrid, m('predmaint_anomaly:anomaly_app:strAdvancedOptions'), 5, 3);

            % Filter Size
            UiWidgetFactory.createLabel(advancedGrid, ...
                m('predmaint_anomaly:anomaly_app:strFilterSize'), 1,...
                m('predmaint_anomaly:anomaly_app:configTooltipFilterSize'));
            limits = [0.9 inf];
            step = 1;
            row = 1;
            roundFractional = true;
            filterSizeSpinner = UiWidgetFactory.createSpinner(advancedGrid, limits, ...
                TS_DeepAnT.defaultModelConfig.FilterSizeSpinner, step, row, roundFractional);
            filterSizeSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'FilterSizeSpinner');

            % Num Filters
            UiWidgetFactory.createLabel(advancedGrid, ...
                m('predmaint_anomaly:anomaly_app:strNumFilters'), 2, ...
                m('predmaint_anomaly:anomaly_app:configTooltipNumberOfFilters'));
            limits = [0.9 inf];
            step = 1;
            row = 2;
            roundFractional = true;
            numFiltersSpinner = UiWidgetFactory.createSpinner(advancedGrid, limits, ...
                TS_DeepAnT.defaultModelConfig.NumFiltersSpinner, step, row, roundFractional);
            numFiltersSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'NumFiltersSpinner');

            % Dropout
            UiWidgetFactory.createLabel(advancedGrid, ...
                m('predmaint_anomaly:anomaly_app:strDropProb'), 3,...
                m('predmaint_anomaly:anomaly_app:configTooltipDropoutProbability'));
            limits = [0 1];
            step = 0.1;
            row = 3;
            roundFractional = false;
            upperLimitInclusive = false;
            lowerLimitInclusive = true;
            dropoutSpinner = UiWidgetFactory.createSpinner(advancedGrid, limits, ...
                TS_DeepAnT.defaultModelConfig.DropoutSpinner, step, row,...
                roundFractional, upperLimitInclusive, lowerLimitInclusive);
            dropoutSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'DropoutSpinner');

            % Revert (Train) button
            parent = mainGrid.Parent; % Revert button should be on the top grid, not the content grid
            row = numel(parent.RowHeight); % Last row
            revertButton = UiWidgetFactory.createRevertButton(weak_obj.Handle, ...
                parent, row, ModelStore, modelName,...
                m('predmaint_anomaly:anomaly_app:strRevert'), true);

            % Persist handles
            wd.Model.MaxEpochsSpinner = maxEpochsSpinner;
            wd.Model.LearnRateSpinner = learnRateSpinner;
            wd.Model.BatchSizeSpinner = batchSizeSpinner;
            wd.Model.ExecEnvDropdown = execEnvDropdown;
            wd.Model.SolverDropdown  = solverDropdown;
            wd.Model.NormalizeDropdown = normalizeDropdown;
            wd.Model.ObservWindowLengthSpinner = observWindowLengthSpinner;
            wd.Model.TrainingStrideSpinner = trainingStrideSpinner;
            wd.Model.DetectWindowLengthSpinner = detectWindowLengthSpinner;
            wd.Model.FilterSizeSpinner = filterSizeSpinner;
            wd.Model.NumFiltersSpinner = numFiltersSpinner;
            wd.Model.DropoutSpinner = dropoutSpinner;
            wd.Model.RevertButton = revertButton;

            PanelOptionsObj.Widgets.Model = wd.Model;
        end

        function createDetectOptionsPanel(PanelOptionsObj, ModelStore, modelName)
            import anomalyAPP.internal.app.modelmanager.utils.*
            import anomalyAPP.internal.app.modelmanager.TS_DeepAnT

            weak_obj = matlab.lang.WeakReference(PanelOptionsObj);
            wd = PanelOptionsObj.Widgets;
            mainGrid = wd.MainGrid;

            % --- Detection Options ---
            detectionGrid = UiWidgetFactory.createGrid(mainGrid, m('predmaint_anomaly:anomaly_app:strDetectionConfig'), 1, 6, Tag="DetectOptsGrid");
            
            % Detection Stride
            UiWidgetFactory.createLabel(detectionGrid, ...
                m('predmaint_anomaly:anomaly_app:strDetectionStride'), 1, ...
                m('predmaint_anomaly:anomaly_app:configTooltipDetectionStride'));
            limits = [0.9 inf];
            step = 1;
            row = 1;
            roundFractional = true;
            detectionStrideSpinner = UiWidgetFactory.createSpinner(detectionGrid, limits, ...
                TS_DeepAnT.defaultDetectConfig.DetectionStrideSpinner, step, row, roundFractional);
            detectionStrideSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipDetectConfig', 'DetectionStrideSpinner');

            % Threshold Method
            UiWidgetFactory.createLabel(detectionGrid, ...
                m('predmaint_anomaly:anomaly_app:strThresMethod'), 2, ...
                m('predmaint_anomaly:anomaly_app:configTooltipThresholdMethod'));
            thresholdMethodDropdown = UiWidgetFactory.createDropdown(detectionGrid, ...
                [m('predmaint_anomaly:anomaly_app:strMean'), ...
                m('predmaint_anomaly:anomaly_app:strMedian'), ...
                m('predmaint_anomaly:anomaly_app:strMax'), ...
                m('predmaint_anomaly:anomaly_app:strContamFrac'), ...
                m('predmaint_anomaly:anomaly_app:strManual'), ...
                m('predmaint_anomaly:anomaly_app:strKSigma')], ...
                {'mean','median','max','contaminationFraction','manual','kSigma'}, ...
                TS_DeepAnT.defaultDetectConfig.ThresholdMethodDropdown, 2, false);
            thresholdMethodDropdown.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipDetectConfig', 'ThresholdMethodDropdown');

            % Threshold Parameter
            UiWidgetFactory.createLabel(detectionGrid, ...
                m('predmaint_anomaly:anomaly_app:strThresParam'), 3, ...
                m('predmaint_anomaly:anomaly_app:configTooltipThresholdParameter'));
            limits = [-inf inf];
            step = 0.5;
            row = 3;
            roundFractional = false;
            thresholdParamSpinner = UiWidgetFactory.createSpinner(detectionGrid, limits, ...
                TS_DeepAnT.defaultDetectConfig.ThresholdParamSpinner, step, row, roundFractional);
            thresholdParamSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipDetectConfig', 'ThresholdParamSpinner');
            thresholdParamSpinner.Tag = "ThresholdParamSpinner";

            % Threshold
            UiWidgetFactory.createLabel(detectionGrid, ...
                m('predmaint_anomaly:anomaly_app:strThreshold'), 4, ...
                m('predmaint_anomaly:anomaly_app:configTooltipThreshold'));
            limits = [-inf inf];
            step = 0.5;
            row = 4;
            roundFractional = false;
            thresholdSpinner = UiWidgetFactory.createSpinner(detectionGrid, limits, ...
                TS_DeepAnT.defaultDetectConfig.ThresholdSpinner, step, row, roundFractional);
            thresholdSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipDetectConfig', 'ThresholdSpinner');
            % Disable at creation since ThresholdMethod is kSigma by
            % default
            thresholdSpinner.Enable = "off";
            thresholdSpinner.Tag = "ThresholdSpinner";

            % Batch Size
            UiWidgetFactory.createLabel(detectionGrid, ...
                m('predmaint_anomaly:anomaly_app:strMiniBatchSize'), 5, ...
                m('predmaint_anomaly:anomaly_app:configTooltipMiniBatchSize'));
            limits = [0.9 inf];
            step = 10;
            row = 5;
            roundFractional = true;
            batchSizeSpinner = UiWidgetFactory.createSpinner(detectionGrid, limits, ...
                TS_DeepAnT.defaultDetectConfig.BatchSizeSpinner, step, row, roundFractional);
            batchSizeSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipDetectConfig', 'BatchSizeSpinner');
            
            % Execution Environment
            UiWidgetFactory.createLabel(detectionGrid, ...
                m('predmaint_anomaly:anomaly_app:strExecEnv'), 6, ...
                m('predmaint_anomaly:anomaly_app:configTooltipExecutionEnvironment'));
            execEnvDropdown = UiWidgetFactory.createDropdown(detectionGrid, [...
                m('predmaint_anomaly:anomaly_app:strAuto'), ...
                m('predmaint_anomaly:anomaly_app:strCpu'), ...
                m('predmaint_anomaly:anomaly_app:strGpu')], ...
                {'auto','cpu','gpu'}, ...
                TS_DeepAnT.defaultDetectConfig.ExecEnvDropdown, 6, false);
            execEnvDropdown.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipDetectConfig', 'ExecEnvDropdown');

            % Revert (Detect) button
            parent = mainGrid.Parent; % Revert button should be on the top grid, not the content grid
            row = numel(parent.RowHeight); % Last row
            revertButton = UiWidgetFactory.createRevertButton(weak_obj.Handle, ...
                parent, row, ModelStore, modelName,...
                m('predmaint_anomaly:anomaly_app:strRevert'), false);

            % Persist handles
            wd.Model.DetectionStrideSpinner = detectionStrideSpinner;
            wd.Model.ThresholdMethodDropdown = thresholdMethodDropdown;
            wd.Model.ThresholdParamSpinner = thresholdParamSpinner;
            wd.Model.ThresholdSpinner = thresholdSpinner;
            wd.Model.BatchSizeSpinner = batchSizeSpinner;
            wd.Model.ExecEnvDropdown = execEnvDropdown;
            wd.Model.RevertButton = revertButton;

            PanelOptionsObj.Widgets.Model = wd.Model;
        end

        function [mdl, monitor] = trainModel(data, cc, host)
            arguments
                data
                cc
                host matlab.ui.container.GridLayout = []
            end

            import anomalyAPP.internal.app.modelmanager.utils.*
            
            if ~isempty(host)
                monitor = MonitorFactory(host);
            else
                monitor = MonitorFactory();
            end

            %For reproducibility
            old = rng;             % save current state (type, seed, substream, etc.)
            restoreRng = onCleanup(@() trainingCleanup(old, monitor));  % restore to previous state
            rng('default');        % set the deterministic default stream
            
            % Train DeepAnT using current training config (cc)
            mdl = deepantAD(size(data{1},2), ...
                "ObservationWindowLength", cc.ObservWindowLengthSpinner, ...
                "TrainingStride", cc.TrainingStrideSpinner, ...
                "DetectionWindowLength", cc.DetectWindowLengthSpinner,...
                "FilterSize", cc.FilterSizeSpinner * ones(1,2), ...
                "NumFilters", cc.NumFiltersSpinner, ...
                "Normalization", cc.NormalizeDropdown, ...
                "DropoutProbability", cc.DropoutSpinner);

            trainOpts = trainingOptions(cc.SolverDropdown, ...
                "ExecutionEnvironment", cc.ExecEnvDropdown, ...
                "Verbose", false, ...
                "MaxEpochs", cc.MaxEpochsSpinner, ...
                "MiniBatchSize", cc.BatchSizeSpinner, ...
                "InitialLearnRate", cc.LearnRateSpinner);

            mdl = train(mdl, data, TrainingOpts=trainOpts, Monitor=monitor.Monitor);

        end

        function [tbl, model] = detect(model, trainData, testData, config, needsConfigUpdate)
            % Detect with DeepAnT using detection config (cc)

            % When called from detect tab, needConfigUpdate is set to true
            % only if tip and LKG are different. config is Tip always in
            % this case.
            % When called from train tab validation metrics,
            % needConfigUpdate is always set to true. config is LKG always
            % in this case.
            if needsConfigUpdate
                % If method is selected to be manual, then update the detector with the current
                % config.
                if config.ThresholdMethodDropdown ==  "manual"
                    model.Model = updateDetector(model.Model, ...
                        "ThresholdMethod", 'manual', ...
                        "Threshold", config.ThresholdSpinner,...
                        "DetectionStride", config.DetectionStrideSpinner,...
                        "MiniBatchSize", config.BatchSizeSpinner,...
                        "ExecutionEnvironment", config.ExecEnvDropdown);
                else
                    model.Model = updateDetector(model.Model, trainData, ...
                        "ThresholdMethod", config.ThresholdMethodDropdown, ...
                        "ThresholdParameter", config.ThresholdParamSpinner, ...
                        "DetectionStride", config.DetectionStrideSpinner,...
                        "MiniBatchSize", config.BatchSizeSpinner,...
                        "ExecutionEnvironment", config.ExecEnvDropdown);
                end
            end

            tbl = detect(model.Model, testData,...
                "MiniBatchSize", config.BatchSizeSpinner,...
                "ExecutionEnvironment", config.ExecEnvDropdown);

            % Downstream functionality assumes that detectionResults are
            % always formatted for member level access
            if ~iscell(tbl)
                tbl = {tbl};
            end
            
            model = model.Handler.updateTipDetectConfig(model);
        end

        function model = updateTipDetectConfig(model)
            if model.TipDetectConfig.ThresholdMethodDropdown ~= "manual"
                % Update the threshold value in both the current config and
                % the LKG config since the model's value changed
                model.TipDetectConfig.ThresholdSpinner = model.Model.Threshold;
                model.LKGDetectConfig.ThresholdSpinner = model.Model.Threshold;
            end
        end

        function [windowLength, detectionStride, obsWinLen] = getCommonWindowDefinitions(model)

            windowLength = model.DetectionWindowLength;
            detectionStride = model.DetectionStride;
            obsWinLen = model.ObservationWindowLength;
        end

        function fillOverviewDiagram(OverviewPanel, modelOverview)

            Dlnet = modelOverview{1};
            
            OverviewAxes = uiaxes(OverviewPanel, 'Visible', 'off',...
                'Units', 'normalized', 'Position', [0 0 1 1],...
                'HitTest', 'off', 'PickableParts', 'none', ...
                'Toolbar', []);

            plot(Dlnet, 'Parent', OverviewAxes);
            set(findall(OverviewAxes,'Type','text'),'FontSize',22)
        end
    end
end

% Local Helper
function s = m(id, varargin)

% Reads string with the given ID from its resource bundle.
s = string(message(id, varargin{:}));
end

% LocalWords:  deepant ObservWindowLengthSpinner ExecEnvDropdown NormalizeDropdown
% LocalWords:  ThresholdMethodDropdown strKSigma strExecEnv strMultigpu strParallelauto
% LocalWords:  strParallelcpu strParallelgpu strObservWL dropdown TipDetectConfig strThresMethod
% LocalWords:  strContamFrac strThresParam adam
