classdef DeepantDetector < anomalyCLI.coder.deepanomaly.AbstractDeepAnomalyDetector
    
   %#codegen

   %   Copyright 2025-2026 The MathWorks, Inc. 

    properties (SetAccess = private)
         ObservationWindowLength
         DetectionWindowLength
         Dlnet
         WindowScoresAggregationMethod
    end

    methods
        function this = DeepantDetector(myProps,baseProps)
            coder.internal.prefer_const(myProps,baseProps);

            % construct base class first.
            this@anomalyCLI.coder.deepanomaly.AbstractDeepAnomalyDetector(baseProps);

            pnames = fieldnames(myProps);
            coder.unroll();
            for i = 1:numel(pnames)
                this.(pnames{i}) = myProps.(pnames{i});
            end
        end

        function [dataArray, targetArray,segmentInfo, dataCell] = iPreProcessData(this, data, stride)
            coder.internal.prefer_const(stride)
            anomalyCLI.internal.utils.TimeSeriesAnomalyProcessing.validateInputData(...
                data, this.NumChannels, this.DetectionWindowLength + this.ObservationWindowLength, this.DetectionStride);

            dataCell1 = anomalyCLI.internal.utils.TimeSeriesAnomalyProcessing.convertDataToCellArray(data);
            dataCell = cellfun(@single,dataCell1, 'UniformOutput',false);
            if ~coder.const(strcmp(this.Normalization,'off'))           
                dataCell = cellfun(@(X)normalize(X,"center",this.DataCenter,"scale",this.DataScale),...
                    dataCell,'UniformOutput',false);
            end

            [dataArray, targetArray, segmentInfo ] = prepareInputs(dataCell,iscell(data), this.ObservationWindowLength,this.DetectionWindowLength,stride);
        end

        function winScores = iGetWinScores(this,datain,target,options)
            arguments
                this 
                datain
                target 
                options.MiniBatchSize
            end
            coder.internal.prefer_const(options);
            data = dlarray(datain,'SCB');
            y = anomalyCLI.coder.utils.miniBatchPredictSCB(...
                this.Dlnet,data,options.MiniBatchSize);
            targetPred = extractdata(reshape(y,this.DetectionWindowLength,this.NumChannels,[]));
            pointScores = this.iComputeAnomalyScore(target,targetPred);
            winScores = double(this.iAggregatePointScores(pointScores));
        end

        function pointScores = iComputeAnomalyScore(~,target,targetPred)
            numObservations = coder.internal.indexInt(size(target,3));
            pointScores = coder.nullcopy(repmat({zeros(size(target,1),1,"like",target)},numObservations,1));
            for i = 1:numObservations
                pointScores{i} = sqrt(sum((target(:,:,i) - targetPred(:,:,i)).^2,2));
            end
        end

        function winScores = iAggregatePointScores(this,pointScores)
            fun = coder.const(str2func(this.WindowScoresAggregationMethod));
            winScores = cellfun(fun,pointScores,'UniformOutput',true);
        end
    end

    methods(Static,Hidden)
        function props = matlabCodegenNontunableProperties(~)          
            props = [{'DetectionWindowLength','ObservationWindowLength','WindowScoresAggregationMethod'},...
                anomalyCLI.coder.deepanomaly.AbstractDeepAnomalyDetector.matlabCodegenNontunableProperties];              
        end

        function name = matlabCodegenUserReadableName()
            % The below name will appear in the report generated by coder.
            name = 'DeepantDetector';
        end      

        function cgObj = matlabCodegenToRedirected(mlObj)
            % mlObj is the DeepantDetector object saved in the matfile. This
            % method is automatically invoked during coder load. Here we
            % convert MATLAB's DeepantDetector object to its coder
            % implementation.

            % Detector must be trained to be used in inference.            
            anomalyCLI.internal.utils.TimeSeriesAnomalyProcessing.validateTrained(...
                mlObj.IsTrained);
            % Concrete class properties
            myProps.DetectionWindowLength = mlObj.DetectionWindowLength;
            myProps.ObservationWindowLength = mlObj.ObservationWindowLength;
            myProps.WindowScoresAggregationMethod = mlObj.getWindowScoresMethod();
            % The last layer is a function layer that does a simple
            % reshape, this layer will not work in code generation, we remove
            % it from the network, to compensate, we will do the necessary
            % reshape after running predict.
            layers = mlObj.Dlnet.Layers;
            myProps.Dlnet = dlnetwork(layers(1:end-1));
            % Base class properties.
            baseProps.NumChannels = mlObj.NumChannels;
            baseProps.Threshold = mlObj.Threshold;
            baseProps.Normalization = mlObj.Normalization;
            baseProps.DetectionStride = mlObj.DetectionStride;
            [baseProps.DataCenter, baseProps.DataScale] = mlObj.getNormalizationParameters();
            cgObj = anomalyCLI.coder.deepanomaly.DeepantDetector(myProps,baseProps);
        end
    end

end

function [dataArray, targetArray, segmentInfo ] = prepareInputs(dataCell,inputDataWascell, observationWindowLength,detectionWindowLength,stride)
coder.internal.prefer_const(inputDataWascell, observationWindowLength,detectionWindowLength,stride);
if coder.const(inputDataWascell)
     [dataArrayCells, targetArrayCells, numWindows, winStartIdx] = cellfun(@(x)createRollingWindows(x,observationWindowLength,detectionWindowLength,stride),...
         dataCell,'UniformOutput',false);
     dataArray = cat(3,dataArrayCells{:});
     targetArray = cat(3,targetArrayCells{:});
     segmentInfo.numWindows = vertcat(numWindows{:});
     segmentInfo.winStartIdx = vertcat(winStartIdx{:});
else
    % avoid using cellfun when original input was not cell to facilitate
    % better constant propagation.
    [dataArray,targetArray,segmentInfo.numWindows, segmentInfo.winStartIdx] = ...
        createRollingWindows(dataCell{1},observationWindowLength,detectionWindowLength,stride);
end
end

function [windowInput,windowTarget,numCompleteWindows, winStartIdx] = createRollingWindows(data,observationWindowLength, detectionWindowLength, stride)
coder.internal.prefer_const(observationWindowLength, detectionWindowLength, stride);
nx = coder.internal.indexInt(size(data,1));
istride = coder.internal.indexInt(stride);
iobservationWindowLength = coder.internal.indexInt(observationWindowLength);
idetectionWindowLength = coder.internal.indexInt(detectionWindowLength);
numCompleteWindows = coder.internal.indexDivide(nx - iobservationWindowLength - idetectionWindowLength,istride) + 1;
windowInput = anomalyCLI.coder.utils.segmentData(data,iobservationWindowLength,istride,numCompleteWindows);
target = data(1+observationWindowLength:end,:);
[windowTarget,~,winStartIdx] = anomalyCLI.coder.utils.segmentData(target, idetectionWindowLength,istride,numCompleteWindows);
winStartIdx = winStartIdx + iobservationWindowLength;
end

