classdef TS_CNNAE
    %Static utility class for CNN Auto-Encoder (CNNAE) model related
    %functionalities like constructing the training & detection
    %configuration panel along with the train and detect actions

    %   Copyright 2025-2026 The MathWorks, Inc.

    properties (Constant)
        Name (1,1) string = m('predmaint_anomaly:anomaly_app:strCNNAE')
        Description (1,1) string = m('predmaint_anomaly:anomaly_app:tipCNNAE')
        Type (1,1) string = "cnnae"
        IconName (1,1) string = "convolution1d"

        % Overview Panel
        ScoringDescription (1,1) string = m('predmaint_anomaly:anomaly_app:descCnnae');
        BestSuitedDescription (1,1) string = m('predmaint_anomaly:anomaly_app:bestSuitedCnnae');
        TuningRecommendationDescription (1,1) string = m('predmaint_anomaly:anomaly_app:tuningRecommendationCnnae');

        % Default configuration values for training and detection
        defaultModelConfig (1,1) struct = struct(...
            'MaxEpochsSpinner', 30, ...
            'LearnRateSpinner', 0.001, ...
            'BatchSizeSpinner', 32, ...
            'ExecEnvDropdown', 'auto', ...
            'FilterSizeSpinner', 7, ...
            'NumFiltersSpinner', 32, ...
            'DropoutSpinner', 0.3, ...
            'DownsampleFactorSpinner', 2, ...
            'NumDownSampleSpinner', 2,...
            'SolverDropdown', 'adam')

        defaultDetectConfig (1,1) struct = struct(...
            'DetectWindowLengthSpinner', 10, ...
            'DetectionStrideSpinner', 10, ...
            'WinLossAggregationDropdown', 'mean', ...
            'ThresholdMethodDropdown', 'mean', ...
            'ThresholdParamSpinner', 3, ...
            'ThresholdSpinner', 1,...
            'BatchSizeSpinner', 32,...
            'ExecEnvDropdown', 'auto')

        %Detector Type
        DetectorType (1,1) string = "DeepLearning"
    end

    methods (Static)
        function createTrainOptionsPanel(PanelOptionsObj, ModelStore, modelName)
            import anomalyAPP.internal.app.modelmanager.utils.UiWidgetFactory
            import anomalyAPP.internal.app.modelmanager.utils.GenericCallbacks
            import anomalyAPP.internal.app.modelmanager.TS_CNNAE

            weak_obj = matlab.lang.WeakReference(PanelOptionsObj);
            wd = PanelOptionsObj.Widgets;
            mainGrid = wd.MainGrid;

            % Create training options panel
            trainingGrid = UiWidgetFactory.createGrid(mainGrid, m('predmaint_anomaly:anomaly_app:strTrainingOptions'), 1, 4, Tag="TrainOptsGrid");

            % Max Epochs
            UiWidgetFactory.createLabel(trainingGrid, ...
                m('predmaint_anomaly:anomaly_app:strMaxEpochs'), 1,...
                m('predmaint_anomaly:anomaly_app:configTooltipMaxEpochs'));
            limits = [0.9, inf];
            step = 1;
            row = 1;
            roundFractional = true;
            maxEpochsSpinner = UiWidgetFactory.createSpinner(trainingGrid, limits,...
                TS_CNNAE.defaultModelConfig.MaxEpochsSpinner, step, row, roundFractional);
            maxEpochsSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'MaxEpochsSpinner');

            % Learning Rate
            UiWidgetFactory.createLabel(trainingGrid, ...
                m('predmaint_anomaly:anomaly_app:strInLR'), 2,...
                m('predmaint_anomaly:anomaly_app:configTooltipInitialLearnRate'));
            limits = [0 inf];
            step = 0.001;
            row = 2;
            roundFractional = false;
            learnRateSpinner = UiWidgetFactory.createSpinner(trainingGrid, limits, ...
                TS_CNNAE.defaultModelConfig.LearnRateSpinner, step, row, roundFractional);
            learnRateSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'LearnRateSpinner');

            % Batch Size
            UiWidgetFactory.createLabel(trainingGrid, ...
                m('predmaint_anomaly:anomaly_app:strMiniBatchSize'), 3,...
                m('predmaint_anomaly:anomaly_app:configTooltipMiniBatchSize'));
            limits = [0.9 inf];
            step = 10;
            row = 3;
            roundFractional = true;
            batchSizeSpinner = UiWidgetFactory.createSpinner(trainingGrid, limits, ...
                TS_CNNAE.defaultModelConfig.BatchSizeSpinner, step, row, roundFractional);
            batchSizeSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'BatchSizeSpinner');

            % Execution Environment
            UiWidgetFactory.createLabel(trainingGrid, ...
                m('predmaint_anomaly:anomaly_app:strExecEnv'), 4,...
                m('predmaint_anomaly:anomaly_app:configTooltipExecutionEnvironment'));
            execEnvDropdown = UiWidgetFactory.createDropdown(trainingGrid, [...
                m('predmaint_anomaly:anomaly_app:strAuto'), ...
                m('predmaint_anomaly:anomaly_app:strCpu'), ...
                m('predmaint_anomaly:anomaly_app:strGpu'), ...
                m('predmaint_anomaly:anomaly_app:strMultigpu')], ...
                {'auto', 'cpu', 'gpu', 'multi-gpu'}, ...
                TS_CNNAE.defaultModelConfig.ExecEnvDropdown, 4, false);
            execEnvDropdown.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'ExecEnvDropdown');

            % Solver Name
            UiWidgetFactory.createLabel(trainingGrid, ...
                m('predmaint_anomaly:anomaly_app:strSolverName'), 5,...
                m('predmaint_anomaly:anomaly_app:configTooltipSolverName'));
            solverDropdown = UiWidgetFactory.createDropdown(trainingGrid, [...
                m('predmaint_anomaly:anomaly_app:strSolverSgdm'), ...
                m('predmaint_anomaly:anomaly_app:strSolverAdam'), ...
                m('predmaint_anomaly:anomaly_app:strSolverRmsprop'), ...
                m('predmaint_anomaly:anomaly_app:strSolverLbfgs'), ...
                m('predmaint_anomaly:anomaly_app:strSolverLm')], ...
                {'sgdm','adam','rmsprop','lbfgs','lm'}, ...
                TS_CNNAE.defaultModelConfig.SolverDropdown, 5, false);
            solverDropdown.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'SolverDropdown');

            % Create model options panel
            modelGrid = UiWidgetFactory.createGrid(mainGrid, m('predmaint_anomaly:anomaly_app:strModelOptionsTitle'), 2, 2, Tag="ModelOptsGrid");

            % Filter Size
            UiWidgetFactory.createLabel(modelGrid, ...
                m('predmaint_anomaly:anomaly_app:strFilterSize'), 1,...
                m('predmaint_anomaly:anomaly_app:configTooltipFilterSize'));
            limits = [0.9 inf];
            step = 1;
            row = 1;
            roundFractional = true;
            filterSizeSpinner = UiWidgetFactory.createSpinner(modelGrid, limits, ...
                TS_CNNAE.defaultModelConfig.FilterSizeSpinner, step, row, roundFractional);
            filterSizeSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'FilterSizeSpinner');

            % Num Filters
            UiWidgetFactory.createLabel(modelGrid, ...
                m('predmaint_anomaly:anomaly_app:strNumFilters'), 2,...
                m('predmaint_anomaly:anomaly_app:configTooltipNumberOfFilters'));
            limits = [0.9 inf];
            step = 1;
            row = 2;
            roundFractional = true;
            numFiltersSpinner = UiWidgetFactory.createSpinner(modelGrid, limits, ...
                TS_CNNAE.defaultModelConfig.NumFiltersSpinner, step, row, roundFractional);
            numFiltersSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'NumFiltersSpinner');

            % Dropout
            UiWidgetFactory.createLabel(modelGrid, ...
                m('predmaint_anomaly:anomaly_app:strDropProb'), 3,...
                m('predmaint_anomaly:anomaly_app:configTooltipDropoutProbability'));
            limits = [0 1];
            step = 0.1;
            row = 3;
            roundFractional = false;
            upperLimitInclusive = true;
            lowerLimitInclusive = true;
            dropoutSpinner = UiWidgetFactory.createSpinner(modelGrid, limits, ...
                TS_CNNAE.defaultModelConfig.DropoutSpinner, step, row, ...
                roundFractional, upperLimitInclusive, lowerLimitInclusive);
            dropoutSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'DropoutSpinner');

            % Downsample Factor
            UiWidgetFactory.createLabel(modelGrid, ...
                m('predmaint_anomaly:anomaly_app:strDownsampleFactor'), 4,...
                m('predmaint_anomaly:anomaly_app:configTooltipDownsampleFactor'));
            limits = [1 100];
            step = 1;
            row = 4;
            roundFractional = true;
            downsampleFactorSpinner = UiWidgetFactory.createSpinner(modelGrid, limits, ...
                TS_CNNAE.defaultModelConfig.DownsampleFactorSpinner, step, row, roundFractional);
            downsampleFactorSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'DownsampleFactorSpinner');

            % Num Downsample Layers
            UiWidgetFactory.createLabel(modelGrid, ...
                m('predmaint_anomaly:anomaly_app:strNumDownSample'), 5,...
                m('predmaint_anomaly:anomaly_app:configTooltipNumberOfDownsampleLayers'));
            limits = [0.9 10000];
            step = 1;
            row = 5;
            roundFractional = true;
            numDownSampleSpinner = UiWidgetFactory.createSpinner(modelGrid, limits, ...
                TS_CNNAE.defaultModelConfig.NumDownSampleSpinner, step, row, roundFractional);
            numDownSampleSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipConfig', 'NumDownSampleSpinner');

            % Revert button
            parent = mainGrid.Parent; % Revert button should be on the top grid, not the content grid
            row = numel(parent.RowHeight); % Last row
            revertButton = UiWidgetFactory.createRevertButton(weak_obj.Handle, ...
                parent, row, ModelStore, modelName,...
                m('predmaint_anomaly:anomaly_app:strRevert'), true);

            % Persist widgets
            wd.Model.MaxEpochsSpinner = maxEpochsSpinner;
            wd.Model.LearnRateSpinner = learnRateSpinner;
            wd.Model.BatchSizeSpinner = batchSizeSpinner;
            wd.Model.ExecEnvDropdown = execEnvDropdown;
            wd.Model.SolverDropdown  = solverDropdown;
            wd.Model.FilterSizeSpinner = filterSizeSpinner;
            wd.Model.NumFiltersSpinner = numFiltersSpinner;
            wd.Model.DropoutSpinner = dropoutSpinner;
            wd.Model.DownsampleFactorSpinner = downsampleFactorSpinner;
            wd.Model.NumDownSampleSpinner = numDownSampleSpinner;
            wd.Model.RevertButton = revertButton;

            PanelOptionsObj.Widgets.Model = wd.Model;
        end

        function createDetectOptionsPanel(PanelOptionsObj, ModelStore, modelName)
            import anomalyAPP.internal.app.modelmanager.utils.*
            import anomalyAPP.internal.app.modelmanager.TS_CNNAE

            weak_obj = matlab.lang.WeakReference(PanelOptionsObj);
            wd = PanelOptionsObj.Widgets;
            mainGrid = wd.MainGrid;

            % Create the detection panel
            detectionGrid = UiWidgetFactory.createGrid(mainGrid, m('predmaint_anomaly:anomaly_app:strDetectionConfig'), 1, 6, Tag="DetectOptsGrid");

            % Detection Window Length
            UiWidgetFactory.createLabel(detectionGrid, ...
                m('predmaint_anomaly:anomaly_app:strDetectWL'), 1, ...
                m('predmaint_anomaly:anomaly_app:configTooltipDetectionWindowLength'));
            limits = [0.9 inf];
            step = 1;
            row = 1;
            roundFractional = true;
            detectWindowLengthSpinner = UiWidgetFactory.createSpinner(detectionGrid, limits, ...
                TS_CNNAE.defaultDetectConfig.DetectWindowLengthSpinner, step, row, roundFractional);
            detectWindowLengthSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipDetectConfig', 'DetectWindowLengthSpinner');

            % Detection Stride
            UiWidgetFactory.createLabel(detectionGrid, ...
                m('predmaint_anomaly:anomaly_app:strDetectionStride'), 2, ...
                m('predmaint_anomaly:anomaly_app:configTooltipDetectionStride'));
            limits = [0.9 inf];
            step = 1;
            row = 2;
            roundFractional = true;
            detectionStrideSpinner = UiWidgetFactory.createSpinner(detectionGrid, limits, ...
                TS_CNNAE.defaultDetectConfig.DetectionStrideSpinner, step, row, roundFractional);
            detectionStrideSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipDetectConfig', 'DetectionStrideSpinner');

            % Threshold Method
            UiWidgetFactory.createLabel(detectionGrid, ...
                m('predmaint_anomaly:anomaly_app:strThresMethod'), 3, ...
                m('predmaint_anomaly:anomaly_app:configTooltipThresholdMethod'));
            thresholdMethodDropdown = UiWidgetFactory.createDropdown(detectionGrid, [...
                m('predmaint_anomaly:anomaly_app:strMean'), ...
                m('predmaint_anomaly:anomaly_app:strMedian'), ...
                m('predmaint_anomaly:anomaly_app:strMax'), ...
                m('predmaint_anomaly:anomaly_app:strContamFrac'), ...
                m('predmaint_anomaly:anomaly_app:strManual') ...
                ], ...
                {'mean','median','max','contaminationFraction','manual'}, ...
                TS_CNNAE.defaultDetectConfig.ThresholdMethodDropdown, 3, false);
            thresholdMethodDropdown.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipDetectConfig', 'ThresholdMethodDropdown');

            % Threshold Parameter
            UiWidgetFactory.createLabel(detectionGrid, ...
                m('predmaint_anomaly:anomaly_app:strThresParam'), 4, ...
                m('predmaint_anomaly:anomaly_app:configTooltipThresholdParameter'));
            limits = [-inf inf];
            step = 0.5;
            row = 4;
            roundFractional = false;
            thresholdParamSpinner = UiWidgetFactory.createSpinner(detectionGrid, limits, ...
                TS_CNNAE.defaultDetectConfig.ThresholdParamSpinner, step, row, roundFractional);
            thresholdParamSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipDetectConfig', 'ThresholdParamSpinner');
            thresholdParamSpinner.Tag = "ThresholdParamSpinner";

            % Threshold
            UiWidgetFactory.createLabel(detectionGrid,  ...
                m('predmaint_anomaly:anomaly_app:strThreshold'), 5, ...
                m('predmaint_anomaly:anomaly_app:configTooltipThreshold'));
            limits = [-inf inf];
            step = 0.5;
            row = 5;
            roundFractional = false;
            thresholdSpinner = UiWidgetFactory.createSpinner(detectionGrid, limits, ...
                TS_CNNAE.defaultDetectConfig.ThresholdSpinner, step, row, roundFractional);
            thresholdSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipDetectConfig', 'ThresholdSpinner');
            % Disable at creation since ThresholdMethod is kSigma by
            % default
            thresholdSpinner.Enable = "off";
            thresholdSpinner.Tag = "ThresholdSpinner";

            % Window Loss Aggregation
            UiWidgetFactory.createLabel(detectionGrid, ...
                m('predmaint_anomaly:anomaly_app:strWinLossAggre'), 6, ...
                m('predmaint_anomaly:anomaly_app:configTooltipWindowLossAggregation'));
            winLossAggregationDropdown = UiWidgetFactory.createDropdown(detectionGrid, [ ...
                m('predmaint_anomaly:anomaly_app:strMax'), ...
                m('predmaint_anomaly:anomaly_app:strMin'), ...
                m('predmaint_anomaly:anomaly_app:strMean'), ...
                m('predmaint_anomaly:anomaly_app:strMedian'), ...
                ] ...
                , {'max', 'min', 'mean', 'median'}, ...
                TS_CNNAE.defaultDetectConfig.WinLossAggregationDropdown, 6, false);
            winLossAggregationDropdown.ValueChangedFcn  = @(es,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipDetectConfig', 'WinLossAggregationDropdown');

            % Batch Size
            UiWidgetFactory.createLabel(detectionGrid, ...
                m('predmaint_anomaly:anomaly_app:strMiniBatchSize'), 7, ...
                m('predmaint_anomaly:anomaly_app:configTooltipMiniBatchSize'));
            limits = [0.9 inf];
            step = 10;
            row = 7;
            roundFractional = true;
            batchSizeSpinner = UiWidgetFactory.createSpinner(detectionGrid, limits, ...
                TS_CNNAE.defaultDetectConfig.BatchSizeSpinner, step, row, roundFractional);
            batchSizeSpinner.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipDetectConfig', 'BatchSizeSpinner');

            % Execution Environment
            UiWidgetFactory.createLabel(detectionGrid, ...
                m('predmaint_anomaly:anomaly_app:strExecEnv'), 8, ...
                m('predmaint_anomaly:anomaly_app:configTooltipExecutionEnvironment'));
            execEnvDropdown = UiWidgetFactory.createDropdown(detectionGrid, [...
                m('predmaint_anomaly:anomaly_app:strAuto'), ...
                m('predmaint_anomaly:anomaly_app:strCpu'), ...
                m('predmaint_anomaly:anomaly_app:strGpu')], ...
                {'auto','cpu','gpu'}, ...
                TS_CNNAE.defaultDetectConfig.ExecEnvDropdown, 8, false);
            execEnvDropdown.ValueChangedFcn = @(~,ed)...
                GenericCallbacks.updateField(ed, ModelStore, modelName, 'TipDetectConfig', 'ExecEnvDropdown');

            % Add the "Revert" button
            parent = mainGrid.Parent; % Revert button should be on the top grid, not the content grid
            row = numel(parent.RowHeight); % Last row
            revertButton = UiWidgetFactory.createRevertButton(weak_obj.Handle, ...
                parent, row, ModelStore, modelName,...
                m('predmaint_anomaly:anomaly_app:strRevert'), false);

            %Persist
            wd.Model.DetectWindowLengthSpinner = detectWindowLengthSpinner;
            wd.Model.DetectionStrideSpinner = detectionStrideSpinner;
            wd.Model.ThresholdMethodDropdown = thresholdMethodDropdown;
            wd.Model.ThresholdParamSpinner = thresholdParamSpinner;
            wd.Model.ThresholdSpinner = thresholdSpinner;
            wd.Model.WinLossAggregationDropdown = winLossAggregationDropdown;
            wd.Model.BatchSizeSpinner = batchSizeSpinner;
            wd.Model.ExecEnvDropdown = execEnvDropdown;
            wd.Model.RevertButton = revertButton;

            PanelOptionsObj.Widgets.Model = wd.Model;
        end


        function [mdl, monitor] = trainModel(data, cc, host)
            arguments
                data
                cc
                host matlab.ui.container.GridLayout = []
            end

            import anomalyAPP.internal.app.modelmanager.utils.*
            
            if ~isempty(host)
                monitor = MonitorFactory(host);
            else
                monitor = MonitorFactory();
            end

            %For reproducibility
            old = rng;             % save current state (type, seed, substream, etc.)
            restoreRng = onCleanup(@() trainingCleanup(old, monitor));  % restore to previous state and delete training progress
            rng('default');        % set the deterministic default stream

            mdl = deepSignalAnomalyDetector(size(data{1},2), ...
                "convautoencoder", ...
                "FilterSize", cc.FilterSizeSpinner, ...
                "NumFilters", cc.NumFiltersSpinner, ...
                "DropoutProbability", cc.DropoutSpinner, ...
                "DownsampleFactor", cc.DownsampleFactorSpinner, ...
                "NumDownsampleLayers", cc.NumDownSampleSpinner);

            trainOpts = trainingOptions(cc.SolverDropdown, ...
                "ExecutionEnvironment", cc.ExecEnvDropdown, ...
                "Verbose", false, ...
                "MaxEpochs", cc.MaxEpochsSpinner, ...
                "MiniBatchSize", cc.BatchSizeSpinner, ...
                "InitialLearnRate", cc.LearnRateSpinner);

            trainDetector(mdl, data, trainOpts, Monitor=monitor.Monitor);
        end

        function [tbl, model] = detect(model, trainData, testData, config, needsConfigUpdate)

            overlapLength = config.DetectWindowLengthSpinner - config.DetectionStrideSpinner;
           
            % When called from detect tab, needConfigUpdate is set to true
            % only if tip and LKG are different. config is Tip always in
            % this case.
            % When called from train tab validation metrics,
            % needConfigUpdate is always set to true. config is LKG always
            % in this case.
            if needsConfigUpdate
                % If method is selected to be manual, then update the detector with the current
                % config.
                if config.ThresholdMethodDropdown ==  "manual"
                    updateDetector(model.Model, ...
                        "ThresholdMethod", 'manual', ...
                        "Threshold", config.ThresholdSpinner, ...
                        "WindowLength", config.DetectWindowLengthSpinner,...
                        "OverlapLength", overlapLength,...
                        "WindowLossAggregation", config.WinLossAggregationDropdown,...
                        "MiniBatchSize", config.BatchSizeSpinner,...
                        "ExecutionEnvironment", config.ExecEnvDropdown);
                else
                    updateDetector(model.Model, trainData, ...
                        "ThresholdMethod", config.ThresholdMethodDropdown, ...
                        "ThresholdParameter", config.ThresholdParamSpinner, ...
                        "WindowLength", config.DetectWindowLengthSpinner,...
                        "OverlapLength", overlapLength,...
                        "WindowLossAggregation", config.WinLossAggregationDropdown,...
                        "MiniBatchSize", config.BatchSizeSpinner,...
                        "ExecutionEnvironment", config.ExecEnvDropdown);
                end
            end

            [labels, scores] =  detect(model.Model, testData,...
                "MiniBatchSize", config.BatchSizeSpinner,...
                "ExecutionEnvironment", config.ExecEnvDropdown);

            tbl = cell(size(labels));
            for iC = 1:numel(labels)
                windowStartIndices = transpose(1:config.DetectionStrideSpinner:size(testData{iC}, 1)); % Not using length to support cases where there are more columns than rows
                tbl{iC, 1} = table(labels{iC}, scores{iC}, windowStartIndices, 'VariableNames', {'Labels', 'AnomalyScores', 'StartIndices'});
            end

            % When called from detect tab - threshold value can change - so
            % both LKG and Tip threshold value needs to change. 
            % For when called from train tab, especially after detect has been
            % called, threshold value can change. For when thresholdmethod
            % is not manual, this should update the LKG and Tip
            % ThresholdValue to represent the new value on the detector. 
            model = model.Handler.updateTipDetectConfig(model);
        end

        function model = updateTipDetectConfig(model)
            if model.TipDetectConfig.ThresholdMethodDropdown ~= "manual"
                % Update the threshold value in both the current config and
                % the LKG config since the model's value changed
                model.TipDetectConfig.ThresholdSpinner = model.Model.Threshold;
                model.LKGDetectConfig.ThresholdSpinner = model.Model.Threshold;
            end
        end

        function [windowLength, detectionStride, obsWinLen] = getCommonWindowDefinitions(model)

            windowLength = model.WindowLength;
            obsWinLen = 0;
            detectionStride = model.WindowLength - model.OverlapLength;
        end

        function fillOverviewDiagram(OverviewPanel, modelOverview)
            
            Dlnet = modelOverview{1};

            OverviewAxes = uiaxes(OverviewPanel, 'Visible', 'off',...
                'Units', 'normalized', 'Position', [0 0 1 1],...
                'HitTest', 'off', 'PickableParts', 'none', ...
                'Toolbar', []);

            plot(Dlnet, 'Parent', OverviewAxes);
            set(findall(OverviewAxes,'Type','text'),'FontSize',22)
        end
    end
end

% Local Helper
function s = m(id, varargin)

% Reads string with the given ID from its resource bundle.
s = string(message(id, varargin{:}));
end

% LocalWords:  cnnae ExecEnvDropdown SolverDropdown WinLossAggregationDropdown
% LocalWords:  ThresholdMethodDropdown strExecEnv strSolverSgdm strSolverRmsprop strSolverLbfgs sgdm
% LocalWords:  adam rmsprop lbfgs TipDetectConfig strThresMethod strContamFrac strThresParam
% LocalWords:  strWinLossAggre convautoencoder
